name: Create HTML

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create folder
        run: mkdir -p html
      - uses: docker://pandoc/core:2.9
        with:
          args: -s --metadata title="Computer Vision" -o html/ComputerVision.html  CViki.md
      - uses: actions/upload-artifact@master
        with:
          name: html
          path: html
